services:
  - type: web
    name: render-flask-sample
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2
    root: .
    envVars:
      - key: FLASK_ENV
        value: production
